name: Python application

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '7 6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 开始
        run: |
          pip install requests

          python3 main.py